formatter: markdown

version: ""

header-from: main.tf
footer-from: ""

recursive:
  enabled: false
  path: modules

sections:
  hide: []
  show: []

content: |-
  {{ .Header }}

  ## Usage

  ```hcl
  module "cluster" {
    source = "github.com/nebari-dev/terraform-aws-eks-cluster"

    project_name = "eks-cluster"

    # VPC configuration
    create_vpc         = true
    availability_zones = ["us-west-2a", "us-west-2b", "us-west-2c"]
    vpc_cidr_block     = "10.10.0.0/16"

    # Cluster configuration
    kubernetes_version        = "1.34"
    endpoint_private_access   = true
    endpoint_public_access    = true
    cluster_enabled_log_types = ["api", "audit", "authenticator", "controllerManager", "scheduler"]
    node_groups = {
      general = {
        instance  = "m6i.large"
        min_nodes = 1
        max_nodes = 5
        disk_size = 100
        labels = {
          role = "general"
        }
      }
      worker = {
        instance  = "t3.medium"
        spot      = true
        min_nodes = 1
        max_nodes = 6
        taints = [{
          key    = "dedicated"
          value  = "batch-jobs"
          effect = "NO_SCHEDULE"
        }]
      }
    }

    # EFS configuration
    efs_enabled          = true
    efs_performance_mode = "generalPurpose"
    efs_throughput_mode  = "elastic"
    efs_encrypted        = true

    # Node security group rules
    # Open ports for Longhorn admission (9502) and conversion (9501) webhooks
    # so the EKS control plane can reach them on the nodes.
    node_security_group_additional_rules = {
      longhorn_webhook_admission = {
        description                   = "Cluster API to Longhorn admission webhook"
        protocol                      = "tcp"
        from_port                     = 9502
        to_port                       = 9502
        type                          = "ingress"
        source_cluster_security_group = true
      }
      longhorn_webhook_conversion = {
        description                   = "Cluster API to Longhorn conversion webhook"
        protocol                      = "tcp"
        from_port                     = 9501
        to_port                       = 9501
        type                          = "ingress"
        source_cluster_security_group = true
      }
    }

    tags = {
      Example = "eks-cluster"
      Project = "terraform-aws-eks-cluster"
    }
  }
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
