formatter: markdown

version: ""

header-from: main.tf
footer-from: ""

recursive:
  enabled: false
  path: modules

sections:
  hide: []
  show: []

content: |-
  {{ .Header }}

  ## Usage

  ```hcl
  module "eks" {
    source = "nebari-dev/terraform-aws-eks-cluster"

    project_name = "cluster-complete"

    # VPC configuration
    create_vpc           = true
    availability_zones   = ["us-west-2a", "us-west-2b", "us-west-2c"]
    vpc_cidr_block       = "10.10.0.0/16"
    create_vpc_endpoints = true

    # Cluster configuration
    kubernetes_version        = "1.34"
    endpoint_private_access   = true
    endpoint_public_access    = true
    cluster_enabled_log_types = ["api", "audit", "authenticator", "controllerManager", "scheduler"]
    node_groups = {
      general = {
        instance  = "m6i.large"
        min_nodes = 1
        max_nodes = 5
        disk_size = 100
      }
      gpu = {
        instance  = "g4dn.xlarge"
        min_nodes = 0
        max_nodes = 3
        gpu       = true
        taints = [{
          key    = "nvidia.com/gpu"
          value  = "true"
          effect = "NO_SCHEDULE"
        }]
      }
      worker = {
        instance  = "t3.medium"
        spot      = true
        min_nodes = 1
        max_nodes = 6
      }
    }

    # EFS configuration
    efs_enabled          = true
    efs_performance_mode = "generalPurpose"
    efs_throughput_mode  = "elastic"
    efs_encrypted        = true

    tags = {
      Example = "cluster-complete"
      Project = "terraform-aws-eks-cluster"
    }
  }
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
